spring:
  jpa:
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://testdb.c2rwzkv3kyqk.eu-central-1.rds.amazonaws.com/testdb
    username: admin
    password: test1234
properties:
  page:
    size: 50